language: java
sudo: false
jdk:
  - oraclejdk8
env:
  matrix:
  - TERM=dumb
  
install:
  - ./gradlew assemble --stacktrace
script:
  - ./gradlew test
after_success:
  - ./gradlew cobertura coveralls
after_failure:
  - cat /home/travis/build/feststelltaste/stagemonitor/stagemonitor-*/hs_err_*.log

cache:
  directories:
  - $HOME/.m2
  - $HOME/.gradle

addons:
  coverity_scan:
    project:
      name: "feststelltaste/stagemonitor"
      description: "Build submitted via Travis CI"
    build_command_prepend: "./gradlew clean"
    build_command: "./gradlew compileJava"
    branch_pattern: coverity
  apt:
    packages:
      - oracle-java8-installer
